"use client";

import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import type { ProcessedResult } from '@/lib/types';

const styles = StyleSheet.create({
  page: { padding: 40, backgroundColor: '#FFFFFF', fontFamily: 'Helvetica' },
  header: { borderBottom: '2pt solid #4B0082', marginBottom: 20, paddingBottom: 10 },
  brand: { fontSize: 24, color: '#4B0082', fontWeight: 'bold' },
  section: { marginBottom: 15 },
  label: { fontSize: 10, color: '#718096', textTransform: 'uppercase', marginBottom: 4 },
  essence: { fontSize: 14, fontStyle: 'italic', color: '#2d3748', marginBottom: 10 },
  keywordsContainer: { flexDirection: 'row', flexWrap: 'wrap', gap: 5, marginBottom: 15 },
  keywordBadge: { backgroundColor: '#F0F8FF', padding: '4 8', borderRadius: 4, fontSize: 10, color: '#4a5568' },
  content: { fontSize: 12, lineHeight: 1.6, color: '#1a202c', textAlign: 'justify' },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, fontSize: 10, textAlign: 'center', color: '#a0aec0' }
});

interface AIScribePDFProps {
    data: ProcessedResult;
}

export const AIScribePDF = ({ data }: AIScribePDFProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.brand}>AirScribe</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.label}>Essence</Text>
        <Text style={styles.essence}>{data.essence}</Text>
      </View>

      {data.keywords.length > 0 && (
        <View style={styles.section}>
            <Text style={styles.label}>Key Vocabulary</Text>
            <View style={styles.keywordsContainer}>
            {data.keywords.map((word, i) => (
                <Text key={i} style={styles.keywordBadge}>{word}</Text>
            ))}
            </View>
        </View>
      )}

      <View style={styles.section}>
        <Text style={styles.label}>Summarized Content</Text>
        <Text style={styles.content}>{data.geminiSummary}</Text>
      </View>

      <Text style={styles.footer}>Generated by AirScribe - {new Date().toLocaleDateString()}</Text>
    </Page>
  </Document>
);
