import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { HelpCircle } from "lucide-react";

export default function HelpPage() {
    return (
        <div className="container mx-auto px-4 py-8">
            <div className="max-w-3xl mx-auto">
                <div className="flex items-center gap-4 mb-8">
                    <HelpCircle className="h-10 w-10 text-primary" />
                    <h1 className="text-4xl font-headline">Help Center</h1>
                </div>

                <Card>
                    <CardHeader>
                        <CardTitle>Frequently Asked Questions</CardTitle>
                    </CardHeader>
                    <CardContent>
                        <Accordion type="single" collapsible className="w-full">
                            <AccordionItem value="item-1">
                                <AccordionTrigger>What is AirScribe ?</AccordionTrigger>
                                <AccordionContent>
                                    AirScribe is a powerful AI tool that helps you process and summarize text. You can customize the tone, quality, and length of the output to fit your needs.
                                </AccordionContent>
                            </AccordionItem>
                            <AccordionItem value="item-2">
                                <AccordionTrigger>How do I use the Workspace?</AccordionTrigger>
                                <AccordionContent>
                                    Simply paste your text into the large text area on the left. Then, use the controls to adjust the AI processing parameters. Click "Process Text" to get your summary.
                                </AccordionContent>
                            </AccordionItem>
                            <AccordionItem value="item-3">
                                <AccordionTrigger>What is the "Intermediate Analysis"?</AccordionTrigger>
                                <AccordionContent>
                                    The "View Intermediate Analysis" toggle allows you to see the initial draft generated by our backend's first-stage model before it's refined by the final AI stage. This can be useful for seeing a different perspective on the source text.
                                </AccordionContent>
                            </AccordionItem>
                            <AccordionItem value="item-4">
                                <AccordionTrigger>Where is my data stored?</AccordionTrigger>
                                <AccordionContent>
                                    For guest users, your processing history is stored locally in your browser's localStorage. This means it's private to your device. Clearing your browser data will erase your history.
                                </AccordionContent>
                            </AccordionItem>
                        </Accordion>
                    </CardContent>
                </Card>
            </div>
        </div>
    );
}
